# automatically added by p10k
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.zsh"
export DISABLE_AUTO_UPDATE="true"
export DISABLE_UPDATE_PROMPT="true"
export MY_DOTFILES_DIR="$HOME/.my_dotfiles"

plugins=(git zsh-autosuggestions zsh-syntax-highlighting zsh-completions z autoupdate)
UPDATE_ZSH_DAYS=16
ZSH_CUSTOM_AUTOUPDATE_QUIET=true
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=60'
if [[ "$(uname)" = "Linux" ]]; then
  ZSH_THEME="philips"
else
  ZSH_THEME="powerlevel10k/powerlevel10k"
fi
source $ZSH/oh-my-zsh.sh
[ -f ~/.z.sh ] && source ~/.z.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

source $MY_DOTFILES_DIR/aliases.sh

if [[ ! -f localdev_venv/bin/activate ]]; then
  pip install uv
  uv venv localdev_venv
fi
source localdev_venv/bin/activate